#!/bin/bash

set -eu

# This standalone installer is generated by scripts/build-installer.sh.
# Edit installer/install-omvi-profile.sh.in or profile/Reolink-OMVI-3i.conf,
# then rebuild it instead of editing this generated file directly.

###############################################################################
# Reolink OMVI 3i profile installer for Synology Surveillance Station
#
# Project and complete documentation:
# https://github.com/MostlyBuilds/synology-surveillance-station-reolink-omvi-3i
#
# IMPORTANT
# ---------------------------------------------------------------------------
# This is an unofficial community project. It is not affiliated with, endorsed
# by, sponsored by, or supported by Synology or Reolink.
#
# USE THIS SCRIPT AT YOUR OWN RISK. It modifies an internal Surveillance
# Station file:
#
#   /var/packages/SurveillanceStation/target/device_pack/camera_support/Reolink.conf
#
# The installer adds or updates the "Reolink OMVI 3i MostlyBuilds" native
# profile inside an owned marker block. Other camera definitions are preserved.
# If the desired file is already installed, nothing is written and Surveillance
# Station is not restarted.
#
# Before saving a change, the installer creates and verifies a timestamped
# backup in a "backups" directory beside this script. Changes use atomic file
# replacement. If Surveillance Station cannot restart, the installer attempts
# to restore the backup.
#
# Store this script in a DSM Shared Folder named:
#
#   Reolink-OMVI-3i-MostlyBuilds
#
# Run with sudo because the target file and package are managed by Surveillance
# Station:
#
#   sudo ./install-omvi-profile.sh             Install or update
#   sudo ./install-omvi-profile.sh --uninstall Remove the profile
#
# IMPORTANT BEHAVIOR
# ---------------------------------------------------------------------------
# - A Device Pack or Surveillance Station update may remove the custom profile.
#   Run this installer again if that happens.
# - Using both the Normal and Auto Track channels may require adding the camera
#   twice and may consume two Surveillance Station camera licenses.
# - Turning the spotlight off through Surveillance Station also disables
#   Reolink Night Smart Mode. Re-enable Night Smart Mode through Reolink if
#   needed.
#
###############################################################################

REOLINK_CONF="/var/packages/SurveillanceStation/target/device_pack/camera_support/Reolink.conf"

PROJECT_URL="https://github.com/MostlyBuilds/synology-surveillance-station-reolink-omvi-3i"

EXPECTED_WORK_DIR_NAME="Reolink-OMVI-3i-MostlyBuilds"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
WORK_DIR="$SCRIPT_DIR"
BACKUP_DIR="${WORK_DIR}/backups"

PROFILE_BEGIN='# BEGIN Reolink-OMVI-3i-MostlyBuilds'
PROFILE_HEADER='[Reolink*OMVI 3i MostlyBuilds]'
PROFILE_END='# END Reolink-OMVI-3i-MostlyBuilds'

ACTION="install"

###############################################################################
# Helpers
###############################################################################

error()
{
    echo "ERROR: $*" >&2
    exit 1
}

count_exact_line()
{
    grep -Fxc "$1" "$2" 2>/dev/null || true
}

usage()
{
    echo "Usage:"
    echo "  sudo ./install-omvi-profile.sh [--install|--uninstall]"
    echo
    echo "Options:"
    echo "  --install      Install or update the MostlyBuilds OMVI 3i profile."
    echo "                 This is the default action."
    echo
    echo "  --uninstall    Remove the MostlyBuilds OMVI 3i profile."
    echo
    echo "  -h, --help     Show this help."
    echo
    echo "Project documentation:"
    echo "  $PROJECT_URL"
}

create_backup()
{
    TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
    BACKUP="$(mktemp "${BACKUP_DIR}/Reolink.conf.${TIMESTAMP}.XXXXXX")"

    echo "Backing up current Reolink.conf:"
    echo "  $BACKUP"

    if ! cp -p "$REOLINK_CONF" "$BACKUP"; then
        rm -f "$BACKUP"
        error "Failed to create backup. Reolink.conf was not modified."
    fi

    if ! cmp -s "$REOLINK_CONF" "$BACKUP"; then
        rm -f "$BACKUP"
        error "Backup verification failed. Reolink.conf was not modified."
    fi

    echo "Backup verified."
}

restore_backup()
{
    echo "Restoring the original Reolink.conf..."

    ROLLBACK_TMP="$(mktemp "${CONF_DIR}/.Reolink.conf.rollback.XXXXXX")"

    if ! cp -p "$BACKUP" "$ROLLBACK_TMP"; then
        rm -f "$ROLLBACK_TMP"
        error "Failed to copy the backup while attempting rollback."
    fi

    chown SurveillanceStation:SurveillanceStation "$ROLLBACK_TMP"
    chmod 644 "$ROLLBACK_TMP"

    if ! mv -f "$ROLLBACK_TMP" "$REOLINK_CONF"; then
        rm -f "$ROLLBACK_TMP"
        error "Failed to restore Reolink.conf from backup: $BACKUP"
    fi

    echo "Original Reolink.conf restored."
}

restart_surveillance_station()
{
    echo
    echo "Restarting Surveillance Station..."

    if synopkg restart SurveillanceStation; then
        return 0
    fi

    return 1
}

###############################################################################
# Command-line arguments
###############################################################################

if [ "$#" -gt 1 ]; then
    usage
    exit 1
fi

if [ "$#" -eq 1 ]; then
    case "$1" in
        --install)
            ACTION="install"
            ;;
        --uninstall)
            ACTION="uninstall"
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo
            usage
            exit 1
            ;;
    esac
fi

###############################################################################
# Preflight checks
###############################################################################

if [ "$(id -u)" -ne 0 ]; then
    error "Run this script with sudo."
fi

if [ "$(basename "$WORK_DIR")" != "$EXPECTED_WORK_DIR_NAME" ]; then
    echo "This installer must be stored in a DSM Shared Folder named:"
    echo "  $EXPECTED_WORK_DIR_NAME"
    echo
    echo "Current installer directory:"
    echo "  $WORK_DIR"
    echo
    echo "Create the required DSM Shared Folder, place this installer inside it,"
    echo "and run it again."
    exit 1
fi

if [ ! -d "$WORK_DIR" ]; then
    error "Installer directory does not exist: $WORK_DIR"
fi

if ! mkdir -p "$BACKUP_DIR"; then
    error "Failed to create backup directory: $BACKUP_DIR"
fi

if [ ! -f "$REOLINK_CONF" ]; then
    echo "Reolink.conf was not found at:"
    echo "  $REOLINK_CONF"
    echo
    echo "The Surveillance Station Device Pack layout may have changed."
    exit 1
fi

if [ ! -r "$REOLINK_CONF" ]; then
    error "Reolink.conf is not readable: $REOLINK_CONF"
fi

if [ ! -w "$REOLINK_CONF" ]; then
    error "Reolink.conf is not writable: $REOLINK_CONF"
fi

CONF_DIR="$(dirname "$REOLINK_CONF")"

if [ ! -d "$CONF_DIR" ]; then
    error "Camera support directory does not exist: $CONF_DIR"
fi

###############################################################################
# Inspect the current Reolink.conf before modifying anything
###############################################################################

BEGIN_COUNT="$(count_exact_line "$PROFILE_BEGIN" "$REOLINK_CONF")"
END_COUNT="$(count_exact_line "$PROFILE_END" "$REOLINK_CONF")"
HEADER_COUNT="$(count_exact_line "$PROFILE_HEADER" "$REOLINK_CONF")"

if [ "$BEGIN_COUNT" -gt 1 ]; then
    error "Found $BEGIN_COUNT copies of the profile BEGIN marker. Reolink.conf requires manual inspection."
fi

if [ "$END_COUNT" -gt 1 ]; then
    error "Found $END_COUNT copies of the profile END marker. Reolink.conf requires manual inspection."
fi

if [ "$HEADER_COUNT" -gt 1 ]; then
    error "Found $HEADER_COUNT copies of the MostlyBuilds OMVI profile header. Reolink.conf requires manual inspection."
fi

# The markers must either both be absent or both be present exactly once.
if [ "$BEGIN_COUNT" -ne "$END_COUNT" ]; then
    echo "The MostlyBuilds profile markers are inconsistent:"
    echo "  BEGIN markers: $BEGIN_COUNT"
    echo "  END markers:   $END_COUNT"
    echo
    echo "No changes were made."
    error "Reolink.conf requires manual inspection."
fi

# If the profile header exists without our markers, do not claim ownership of
# it or attempt to remove it.
if [ "$BEGIN_COUNT" -eq 0 ] && [ "$HEADER_COUNT" -ne 0 ]; then
    echo "The profile header exists without the MostlyBuilds BEGIN/END markers:"
    echo "  $PROFILE_HEADER"
    echo
    echo "The installer will not assume that this profile is safe to modify."
    echo "No changes were made."
    error "Reolink.conf requires manual inspection."
fi

# If our marker block exists, it must contain exactly one expected header.
if [ "$BEGIN_COUNT" -eq 1 ] && [ "$HEADER_COUNT" -ne 1 ]; then
    echo "The MostlyBuilds marker block exists, but the expected profile header"
    echo "was not found exactly once."
    echo
    echo "No changes were made."
    error "Reolink.conf requires manual inspection."
fi

# If our block exists, verify its ordering.
if [ "$BEGIN_COUNT" -eq 1 ]; then
    BEGIN_LINE="$(grep -Fn "$PROFILE_BEGIN" "$REOLINK_CONF" | cut -d: -f1)"
    HEADER_LINE="$(grep -Fn "$PROFILE_HEADER" "$REOLINK_CONF" | cut -d: -f1)"
    END_LINE="$(grep -Fn "$PROFILE_END" "$REOLINK_CONF" | cut -d: -f1)"

    if [ "$BEGIN_LINE" -ge "$HEADER_LINE" ] ||
       [ "$HEADER_LINE" -ge "$END_LINE" ]; then
        echo "Profile marker/header order is invalid:"
        echo "  BEGIN line:  $BEGIN_LINE"
        echo "  HEADER line: $HEADER_LINE"
        echo "  END line:    $END_LINE"
        echo
        echo "No changes were made."
        error "Reolink.conf requires manual inspection."
    fi
fi

###############################################################################
# Uninstall
###############################################################################

if [ "$ACTION" = "uninstall" ]; then

    if [ "$BEGIN_COUNT" -eq 0 ]; then
        echo "The MostlyBuilds OMVI profile is not installed."
        echo "No changes were necessary."
        exit 0
    fi

    TMP="$(mktemp "${CONF_DIR}/.Reolink.conf.mostlybuilds.XXXXXX")"

    cleanup()
    {
        rm -f "$TMP"
    }

    trap cleanup EXIT HUP INT TERM

    # Remove only the block owned by this installer. Trailing blank lines are
    # normalized after removing the custom profile.
    awk -v begin="$PROFILE_BEGIN" -v end="$PROFILE_END" '
    BEGIN {
        skipping = 0
        pending_blank_lines = 0
    }

    $0 == begin {
        skipping = 1
        next
    }

    skipping && $0 == end {
        skipping = 0
        next
    }

    skipping {
        next
    }

    $0 ~ /^[[:space:]]*$/ {
        pending_blank_lines++
        next
    }

    {
        while (pending_blank_lines > 0) {
            print ""
            pending_blank_lines--
        }

        print
    }
    ' "$REOLINK_CONF" > "$TMP"

    if [ ! -s "$TMP" ]; then
        error "Generated Reolink.conf is empty. No changes were made."
    fi

    if [ "$(count_exact_line "$PROFILE_BEGIN" "$TMP")" -ne 0 ] ||
       [ "$(count_exact_line "$PROFILE_HEADER" "$TMP")" -ne 0 ] ||
       [ "$(count_exact_line "$PROFILE_END" "$TMP")" -ne 0 ]; then
        error "Failed to cleanly remove the MostlyBuilds profile. No changes were made."
    fi

    if cmp -s "$TMP" "$REOLINK_CONF"; then
        echo "The MostlyBuilds OMVI profile is already absent."
        echo "No changes were necessary."
        exit 0
    fi

    create_backup

    chown SurveillanceStation:SurveillanceStation "$TMP"
    chmod 644 "$TMP"

    echo
    echo "Removing profile:"
    echo "  $PROFILE_HEADER"

    mv -f "$TMP" "$REOLINK_CONF"
    trap - EXIT HUP INT TERM

    if ! restart_surveillance_station; then
        echo
        echo "ERROR: Surveillance Station failed to restart after uninstalling"
        echo "the custom profile."
        echo

        restore_backup

        echo "Attempting to restart Surveillance Station with the original file..."

        if synopkg restart SurveillanceStation; then
            echo "Surveillance Station restarted successfully after rollback."
        else
            echo "WARNING: Surveillance Station also failed to restart after rollback."
            echo "Manual investigation is required."
        fi

        exit 1
    fi

    echo
    echo "Successfully uninstalled:"
    echo "  $PROFILE_HEADER"

    echo
    echo "Backup:"
    echo "  $BACKUP"

    echo
    echo "Done."

    exit 0
fi

###############################################################################
# Install / update
###############################################################################

TMP="$(mktemp "${CONF_DIR}/.Reolink.conf.mostlybuilds.XXXXXX")"

cleanup()
{
    rm -f "$TMP"
}

trap cleanup EXIT HUP INT TERM

# Remove the existing profile owned by this installer, if present.
#
# The current profile embedded below is then appended. This makes installation
# idempotent and also allows future versions of this script to update an
# existing profile simply by being run again.
#
# Blank lines outside the custom profile are preserved, except for trailing
# blank lines at the end of the file. Those are normalized so exactly one blank
# separator exists before the MostlyBuilds profile.
awk -v begin="$PROFILE_BEGIN" -v end="$PROFILE_END" '
BEGIN {
    skipping = 0
    pending_blank_lines = 0
}

$0 == begin {
    skipping = 1
    next
}

skipping && $0 == end {
    skipping = 0
    next
}

skipping {
    next
}

$0 ~ /^[[:space:]]*$/ {
    pending_blank_lines++
    next
}

{
    while (pending_blank_lines > 0) {
        print ""
        pending_blank_lines--
    }

    print
}
' "$REOLINK_CONF" > "$TMP"

# Add exactly one blank separator between the Synology content and the custom
# MostlyBuilds profile.
printf '\n' >> "$TMP"

cat >> "$TMP" <<'EOF'
# BEGIN Reolink-OMVI-3i-MostlyBuilds
[Reolink*OMVI 3i MostlyBuilds]
{BasicSettings}
    api = reolinkv1
    https_connection = yes
    channel_list = Normal,Auto Track
    multi_channel_audio = Normal,Auto Track
    firmware_version = v3.2.0.6905_2607301172
    multi_streams = 2
    h264 = rtsp
    h265 = rtsp
    rtsp_protocol = auto,tcp,udp
    default_rtsp_protocol = tcp
    key_frame_interval_range = second,1-2
    audio_format = AAC
    audio_output_format = PCMU/8000/8/1
    camera_parameters = yes
    ntp_server = Surveillance Station,pool.ntp.org,time.windows.com,time-a.nist.gov,time-b.nist.gov,time-nw.nist.gov,disable
    osd_timestamp = yes
    osd_format = datetime,text
    osd_position = top_left,top,top_right,bottom_left,bottom,bottom_right
    exposure_control = 50,60,none
    exposure_mode = auto,day,night
    video_mirror = yes
    video_flip = yes
    motion = h264,h265
    motion_param = sensitivity
    ptz_direction = 8
    ptz_speed_config = speed_url
    ptz_speed_max = 64
    preset = 64
    pan = continuous
    tilt = continuous
    external_function = led
    default_username = admin
    activate_time = 150
    force_restart_time = 150
    api_specific = SET_MD_V2,QUERY_RTSP_PATH,AO_FRAME_SIZE:1024,AO_SET_MARKER
    device_limitation_notes = svs_support_h265_stream1_h264_stream2

{Normal,stream_1}
    resolutions_h265 = 5120x1920
    fps_h265_5120x1920 = 2,4,6,8,10,12,15,16,18,20
    bitrate_control_h265 = cbr
    cbr_list_h265 = 3072,4096,5120,6144,7168,8192

{Normal,stream_2}
    resolutions_h264 = 1920x720
    fps_h264_1920x720 = 4,6,8,10,12,15,16,18,20
    bitrate_control_h264 = cbr
    cbr_list_h264 = 256,384,512,768,1024,1228,1536,2048

{Auto Track,stream_1}
    resolutions_h265 = 3840x2160
    fps_h265_3840x2160 = 2,4,6,8,10,12,15,16,18,20
    bitrate_control_h265 = cbr
    cbr_list_h265 = 3072,4096,5120,6144,7168

{Auto Track,stream_2}
    resolutions_h264 = 896x512
    fps_h264_896x512 = 4,6,8,10,12,15,16,18,20
    bitrate_control_h264 = cbr
    cbr_list_h264 = 256,384,512,672,768,1024,1228

# END Reolink-OMVI-3i-MostlyBuilds
EOF

###############################################################################
# Validate the generated file before replacing anything
###############################################################################

NEW_BEGIN_COUNT="$(count_exact_line "$PROFILE_BEGIN" "$TMP")"
NEW_END_COUNT="$(count_exact_line "$PROFILE_END" "$TMP")"
NEW_HEADER_COUNT="$(count_exact_line "$PROFILE_HEADER" "$TMP")"

if [ "$NEW_BEGIN_COUNT" -ne 1 ]; then
    error "Generated file contains $NEW_BEGIN_COUNT BEGIN markers; expected exactly 1."
fi

if [ "$NEW_END_COUNT" -ne 1 ]; then
    error "Generated file contains $NEW_END_COUNT END markers; expected exactly 1."
fi

if [ "$NEW_HEADER_COUNT" -ne 1 ]; then
    error "Generated file contains $NEW_HEADER_COUNT profile headers; expected exactly 1."
fi

if [ ! -s "$TMP" ]; then
    error "Generated Reolink.conf is empty."
fi

NEW_BEGIN_LINE="$(grep -Fn "$PROFILE_BEGIN" "$TMP" | cut -d: -f1)"
NEW_HEADER_LINE="$(grep -Fn "$PROFILE_HEADER" "$TMP" | cut -d: -f1)"
NEW_END_LINE="$(grep -Fn "$PROFILE_END" "$TMP" | cut -d: -f1)"

if [ "$NEW_BEGIN_LINE" -ge "$NEW_HEADER_LINE" ] ||
   [ "$NEW_HEADER_LINE" -ge "$NEW_END_LINE" ]; then
    error "Generated profile markers/header are in an invalid order."
fi

###############################################################################
# Avoid rewriting/restarting if the desired profile is already installed
###############################################################################

if cmp -s "$TMP" "$REOLINK_CONF"; then
    echo
    echo "The MostlyBuilds OMVI profile is already installed and up to date."
    echo "No changes were necessary."
    exit 0
fi

###############################################################################
# Backup
###############################################################################

create_backup

###############################################################################
# Install atomically
###############################################################################

chown SurveillanceStation:SurveillanceStation "$TMP"
chmod 644 "$TMP"

echo
echo "Installing profile:"
echo "  $PROFILE_HEADER"

mv -f "$TMP" "$REOLINK_CONF"

# TMP no longer exists after the successful atomic rename.
trap - EXIT HUP INT TERM

###############################################################################
# Verify installed file
###############################################################################

INSTALLED_BEGIN_COUNT="$(count_exact_line "$PROFILE_BEGIN" "$REOLINK_CONF")"
INSTALLED_HEADER_COUNT="$(count_exact_line "$PROFILE_HEADER" "$REOLINK_CONF")"
INSTALLED_END_COUNT="$(count_exact_line "$PROFILE_END" "$REOLINK_CONF")"

if [ "$INSTALLED_BEGIN_COUNT" -ne 1 ] ||
   [ "$INSTALLED_HEADER_COUNT" -ne 1 ] ||
   [ "$INSTALLED_END_COUNT" -ne 1 ]; then

    echo
    echo "ERROR: Post-install verification failed."
    echo

    restore_backup

    error "Installation failed and the original Reolink.conf was restored."
fi

###############################################################################
# Restart Surveillance Station
###############################################################################

if ! restart_surveillance_station; then

    echo
    echo "ERROR: Surveillance Station failed to restart after installing the"
    echo "custom profile."
    echo

    restore_backup

    echo "Attempting to restart Surveillance Station with the original file..."

    if synopkg restart SurveillanceStation; then
        echo "Surveillance Station restarted successfully after rollback."
    else
        echo "WARNING: Surveillance Station also failed to restart after rollback."
        echo "Manual investigation is required."
    fi

    exit 1
fi

###############################################################################
# Done
###############################################################################

echo
echo "Successfully installed:"
echo "  $PROFILE_HEADER"

echo
echo "Backup:"
echo "  $BACKUP"

echo
echo "NOTE:"
echo "  A future Surveillance Station Device Pack update may replace Reolink.conf."
echo "  If the custom profile disappears, run this installer again."

echo
echo "Done."
