# BEGIN Reolink-OMVI-3i-MostlyBuilds
[Reolink*OMVI 3i MostlyBuilds]
{BasicSettings}
    api = reolinkv1
    https_connection = yes
    channel_list = Normal,Auto Track
    multi_channel_audio = Normal,Auto Track
    firmware_version = v3.2.0.6905_2607301172
    multi_streams = 2
    h264 = rtsp
    h265 = rtsp
    rtsp_protocol = auto,tcp,udp
    default_rtsp_protocol = tcp
    key_frame_interval_range = second,1-2
    audio_format = AAC
    audio_output_format = PCMU/8000/8/1
    camera_parameters = yes
    ntp_server = Surveillance Station,pool.ntp.org,time.windows.com,time-a.nist.gov,time-b.nist.gov,time-nw.nist.gov,disable
    osd_timestamp = yes
    osd_format = datetime,text
    osd_position = top_left,top,top_right,bottom_left,bottom,bottom_right
    exposure_control = 50,60,none
    exposure_mode = auto,day,night
    video_mirror = yes
    video_flip = yes
    motion = h264,h265
    motion_param = sensitivity
    ptz_direction = 8
    ptz_speed_config = speed_url
    ptz_speed_max = 64
    preset = 64
    pan = continuous
    tilt = continuous
    external_function = led
    default_username = admin
    activate_time = 150
    force_restart_time = 150
    api_specific = SET_MD_V2,QUERY_RTSP_PATH,AO_FRAME_SIZE:1024,AO_SET_MARKER
    device_limitation_notes = svs_support_h265_stream1_h264_stream2

{Normal,stream_1}
    resolutions_h265 = 5120x1920
    fps_h265_5120x1920 = 2,4,6,8,10,12,15,16,18,20
    bitrate_control_h265 = cbr
    cbr_list_h265 = 3072,4096,5120,6144,7168,8192

{Normal,stream_2}
    resolutions_h264 = 1920x720
    fps_h264_1920x720 = 4,6,8,10,12,15,16,18,20
    bitrate_control_h264 = cbr
    cbr_list_h264 = 256,384,512,768,1024,1228,1536,2048

{Auto Track,stream_1}
    resolutions_h265 = 3840x2160
    fps_h265_3840x2160 = 2,4,6,8,10,12,15,16,18,20
    bitrate_control_h265 = cbr
    cbr_list_h265 = 3072,4096,5120,6144,7168

{Auto Track,stream_2}
    resolutions_h264 = 896x512
    fps_h264_896x512 = 4,6,8,10,12,15,16,18,20
    bitrate_control_h264 = cbr
    cbr_list_h264 = 256,384,512,672,768,1024,1228

# END Reolink-OMVI-3i-MostlyBuilds
